import typing

from semvertag._types import CheckResult, Commit, Tag


class Provider(typing.Protocol):
    name: str

    def get_default_branch(self) -> str: ...
    def get_latest_commit_on_default_branch(self) -> Commit: ...
    def list_tags(self) -> list[Tag]: ...
    def create_tag(self, name: str, commit_sha: str) -> None: ...

    def check_token(self) -> CheckResult: ...
    def check_scopes(self) -> CheckResult: ...
    def check_project_access(self) -> CheckResult: ...
    def check_protected_tags(self) -> CheckResult: ...


__all__: typing.Final = ("Provider",)
